POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsYW50IiwiaWQiOiI1ZTBjZjA0MmNkOTRhYTBhMTg1YzY0MzMiLCJpYXQiOjE1Nzc5MDY4MTh9.hsJhwS98fb9Xbkz1AkXrW6eRC0nA-DaMxm4uumJEbCg

{
    "title":"origin of species",
    "author":"charles darwin",
    "url":"localhost.com",
    "likes":5001
}